### PR TITLE
Update icon to breeze version

### PR DESCRIPTION
**Pull request by Siosm**
Temporary workaround until upstream PR https://invent.kde.org/sdk/kcachegrind/-/merge_requests/1 is merged.

### CODE REVIEW

**Comment by Siosm** [comment]
LGTM

**Comment by tsdgeos** [comment]
I'm kind of unconvinced we should do this before upstream approves.

What do others think? @aleixpol @grulja

**Comment by travier** [comment]
Sure, let's wait for upstream PR to get merged.

**Comment by Siosm** [comment]
Sure, let's wait for upstream before getting this one merged.

**Comment by Siosm** [comment]
This is fixed via the latest release.

**Pull request closed without merging**
